name: Test
on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  GITHUB: True

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0

      - name: Test
        run: "deno test -A"
